// A small curated catalog used to generate viable trip options from group
// preferences. Purely demo data — the scoring/synthesis logic in tripLogic.js
// is fully generic and knows nothing about these specific places.
export const DESTINATIONS = [
  { name: 'Goa', types: ['Beach', 'Nightlife', 'Relaxation'], activities: ['Food', 'Nightlife', 'Water sports', 'Cafés', 'Shopping'], vibes: ['Relaxed', 'Party-focused', 'Food-focused', 'Spontaneous'], budgetMin: 15000, budgetMax: 30000, travelModes: ['Flight', 'Train', 'Road'], travelTimeHours: 3, domestic: true },
  { name: 'Bali, Indonesia', types: ['Beach', 'Nature', 'Cultural', 'Adventure', 'Romantic'], activities: ['Sightseeing', 'Water sports', 'Wellness', 'Cafés', 'Culture'], vibes: ['Relaxed', 'Luxury', 'Slow', 'Adventure-heavy'], budgetMin: 45000, budgetMax: 90000, travelModes: ['Flight'], travelTimeHours: 8, domestic: false },
  { name: 'Thailand (Phuket/Bangkok)', types: ['Beach', 'City', 'Nightlife'], activities: ['Nightlife', 'Food', 'Shopping', 'Water sports', 'Sightseeing'], vibes: ['Party-focused', 'Spontaneous', 'Budget-friendly'], budgetMin: 35000, budgetMax: 65000, travelModes: ['Flight'], travelTimeHours: 5, domestic: false },
  { name: 'Vietnam', types: ['Nature', 'Cultural', 'Adventure', 'City'], activities: ['Sightseeing', 'Food', 'Adventure', 'Culture', 'Road trips'], vibes: ['Adventure-heavy', 'Budget-friendly', 'Slow'], budgetMin: 40000, budgetMax: 70000, travelModes: ['Flight'], travelTimeHours: 6, domestic: false },
  { name: 'Sri Lanka', types: ['Beach', 'Nature', 'Cultural'], activities: ['Sightseeing', 'Food', 'Road trips', 'Water sports', 'Wellness'], vibes: ['Relaxed', 'Slow', 'Planned'], budgetMin: 40000, budgetMax: 75000, travelModes: ['Flight'], travelTimeHours: 3, domestic: false },
  { name: 'Manali', types: ['Mountains', 'Adventure', 'Nature'], activities: ['Trekking', 'Adventure', 'Sightseeing', 'Cafés', 'Road trips'], vibes: ['Adventure-heavy', 'Slow', 'Spontaneous'], budgetMin: 12000, budgetMax: 25000, travelModes: ['Road', 'Flight'], travelTimeHours: 12, domestic: true },
  { name: 'Shimla', types: ['Mountains', 'Nature', 'Relaxation'], activities: ['Sightseeing', 'Cafés', 'Road trips', 'Relaxing'], vibes: ['Relaxed', 'Slow', 'Planned'], budgetMin: 10000, budgetMax: 20000, travelModes: ['Road', 'Train'], travelTimeHours: 8, domestic: true },
  { name: 'Rishikesh', types: ['Mountains', 'Adventure', 'Nature'], activities: ['Adventure', 'Wellness', 'Trekking', 'Water sports'], vibes: ['Adventure-heavy', 'Slow', 'Budget-friendly'], budgetMin: 8000, budgetMax: 18000, travelModes: ['Road', 'Train'], travelTimeHours: 7, domestic: true },
  { name: 'Coorg', types: ['Mountains', 'Nature', 'Relaxation', 'Romantic'], activities: ['Sightseeing', 'Trekking', 'Cafés', 'Relaxing'], vibes: ['Relaxed', 'Slow'], budgetMin: 10000, budgetMax: 22000, travelModes: ['Road'], travelTimeHours: 6, domestic: true },
  { name: 'Munnar & Kerala backwaters', types: ['Nature', 'Relaxation', 'Cultural', 'Romantic'], activities: ['Sightseeing', 'Relaxing', 'Wellness', 'Food'], vibes: ['Relaxed', 'Slow', 'Luxury'], budgetMin: 15000, budgetMax: 32000, travelModes: ['Flight', 'Road'], travelTimeHours: 6, domestic: true },
  { name: 'Andaman Islands', types: ['Beach', 'Nature', 'Adventure', 'Romantic'], activities: ['Water sports', 'Sightseeing', 'Relaxing', 'Adventure'], vibes: ['Relaxed', 'Luxury', 'Slow'], budgetMin: 30000, budgetMax: 55000, travelModes: ['Flight'], travelTimeHours: 4, domestic: true },
  { name: 'Udaipur', types: ['Cultural', 'City', 'Relaxation', 'Romantic'], activities: ['Sightseeing', 'Culture', 'Food', 'Shopping', 'Cafés'], vibes: ['Relaxed', 'Luxury', 'Planned'], budgetMin: 15000, budgetMax: 35000, travelModes: ['Flight', 'Train', 'Road'], travelTimeHours: 4, domestic: true },
  { name: 'Jaipur', types: ['Cultural', 'City'], activities: ['Sightseeing', 'Culture', 'Shopping', 'Food'], vibes: ['Planned', 'Budget-friendly', 'Packed'], budgetMin: 10000, budgetMax: 22000, travelModes: ['Flight', 'Train', 'Road'], travelTimeHours: 5, domestic: true },
  { name: 'Meghalaya (Northeast India)', types: ['Nature', 'Adventure', 'Mountains'], activities: ['Trekking', 'Sightseeing', 'Adventure', 'Road trips'], vibes: ['Slow', 'Adventure-heavy', 'Spontaneous'], budgetMin: 18000, budgetMax: 35000, travelModes: ['Flight', 'Road'], travelTimeHours: 8, domestic: true },
  { name: 'Dubai, UAE', types: ['City', 'Nightlife', 'Adventure'], activities: ['Shopping', 'Nightlife', 'Sightseeing', 'Adventure', 'Food'], vibes: ['Luxury', 'Packed', 'Party-focused'], budgetMin: 55000, budgetMax: 110000, travelModes: ['Flight'], travelTimeHours: 4, domestic: false },
  { name: 'Singapore', types: ['City', 'Cultural'], activities: ['Sightseeing', 'Food', 'Shopping', 'Culture'], vibes: ['Planned', 'Luxury', 'Packed'], budgetMin: 60000, budgetMax: 120000, travelModes: ['Flight'], travelTimeHours: 6, domestic: false },
  { name: 'Ladakh', types: ['Mountains', 'Adventure', 'Nature'], activities: ['Road trips', 'Trekking', 'Adventure', 'Sightseeing'], vibes: ['Adventure-heavy', 'Slow', 'Spontaneous'], budgetMin: 25000, budgetMax: 45000, travelModes: ['Flight', 'Road'], travelTimeHours: 10, domestic: true },
  { name: 'Pondicherry', types: ['Beach', 'Cultural', 'Relaxation', 'Romantic'], activities: ['Cafés', 'Sightseeing', 'Relaxing', 'Culture'], vibes: ['Relaxed', 'Slow', 'Budget-friendly'], budgetMin: 10000, budgetMax: 20000, travelModes: ['Road', 'Train'], travelTimeHours: 3, domestic: true },
  { name: 'Hampi', types: ['Cultural', 'Adventure', 'Nature'], activities: ['Sightseeing', 'Culture', 'Adventure', 'Trekking'], vibes: ['Slow', 'Spontaneous', 'Budget-friendly'], budgetMin: 8000, budgetMax: 16000, travelModes: ['Train', 'Road'], travelTimeHours: 8, domestic: true },
  { name: 'Kasol & Parvati Valley', types: ['Mountains', 'Nature', 'Adventure'], activities: ['Trekking', 'Cafés', 'Adventure', 'Relaxing'], vibes: ['Slow', 'Spontaneous', 'Budget-friendly'], budgetMin: 9000, budgetMax: 18000, travelModes: ['Road'], travelTimeHours: 12, domestic: true },
]
