// A small curated catalog used to generate viable trip options from group
// preferences. Purely demo data — the scoring/synthesis logic in tripLogic.js
// is fully generic and knows nothing about these specific places.
//
// `profile` gives each destination a 0-1 strength on every selectable
// "kind of place" axis (not just a yes/no tag) — this is what lets the
// engine compute a real preference-fit score instead of a keyword match,
// and what lets two travellers with different picks (e.g. Mountains vs.
// Beach) both score a destination that's genuinely strong on both.
//
// `highlights` gives a short, destination-specific reason for each axis
// where it's actually strong (profile >= 0.6) — used to explain *why* a
// destination fits someone's pick, grounded in the place's own
// characteristics rather than a generic sentence.
export const DESTINATIONS = [
  {
    name: 'Goa',
    profile: { Beach: 0.9, Mountains: 0.05, City: 0.3, 'Parks & nature': 0.2, Cultural: 0.2, Adventure: 0.3, Nightlife: 0.85, Romantic: 0.5 },
    highlights: { Beach: 'the North and South Goa beach belt', Nightlife: 'the beach shacks and club scene in Baga/Anjuna' },
    activities: ['Food', 'Nightlife', 'Water sports', 'Cafés', 'Shopping'],
    budgetMin: 15000, budgetMax: 30000,
    travelModes: ['Flight', 'Train', 'Road'], travelTimeHours: 3, domestic: true,
    recommendedDuration: { min: 3, max: 5 }, typicalPace: 'either',
    suitableStayTypes: ['hotel', 'rental'],
  },
  {
    name: 'Bali, Indonesia',
    profile: { Beach: 0.8, Mountains: 0.3, City: 0.3, 'Parks & nature': 0.7, Cultural: 0.7, Adventure: 0.6, Nightlife: 0.4, Romantic: 0.85 },
    highlights: { Beach: 'Uluwatu and Seminyak’s coastline', 'Parks & nature': 'the Ubud rice terraces and jungle', Cultural: 'Hindu temples like Tanah Lot', Romantic: 'villa stays and honeymoon resorts' },
    activities: ['Sightseeing', 'Water sports', 'Wellness', 'Cafés', 'Culture'],
    budgetMin: 45000, budgetMax: 90000,
    travelModes: ['Flight'], travelTimeHours: 8, domestic: false,
    recommendedDuration: { min: 5, max: 8 }, typicalPace: 'slow',
    suitableStayTypes: ['hotel', 'rental'],
  },
  {
    name: 'Thailand (Phuket/Bangkok)',
    profile: { Beach: 0.7, Mountains: 0.1, City: 0.7, 'Parks & nature': 0.3, Cultural: 0.4, Adventure: 0.4, Nightlife: 0.85, Romantic: 0.4 },
    highlights: { Beach: 'Phuket’s Patong and Karon beaches', City: 'Bangkok’s street markets and skyline', Nightlife: 'Bangla Road and Bangkok’s nightlife district' },
    activities: ['Nightlife', 'Food', 'Shopping', 'Water sports', 'Sightseeing'],
    budgetMin: 35000, budgetMax: 65000,
    travelModes: ['Flight'], travelTimeHours: 5, domestic: false,
    recommendedDuration: { min: 5, max: 7 }, typicalPace: 'packed',
    suitableStayTypes: ['hotel'],
  },
  {
    name: 'Vietnam',
    profile: { Beach: 0.4, Mountains: 0.4, City: 0.6, 'Parks & nature': 0.7, Cultural: 0.75, Adventure: 0.6, Nightlife: 0.3, Romantic: 0.3 },
    highlights: { 'Parks & nature': 'Ha Long Bay’s limestone karsts', Cultural: 'Hanoi’s old quarter and Hoi An’s ancient town', City: 'Ho Chi Minh City’s street life' },
    activities: ['Sightseeing', 'Food', 'Adventure', 'Culture', 'Road trips'],
    budgetMin: 40000, budgetMax: 70000,
    travelModes: ['Flight'], travelTimeHours: 6, domestic: false,
    recommendedDuration: { min: 6, max: 9 }, typicalPace: 'packed',
    suitableStayTypes: ['hotel'],
  },
  {
    name: 'Sri Lanka',
    profile: { Beach: 0.7, Mountains: 0.4, City: 0.3, 'Parks & nature': 0.7, Cultural: 0.6, Adventure: 0.4, Nightlife: 0.2, Romantic: 0.6 },
    highlights: { Beach: 'Mirissa and Unawatuna’s coastline', 'Parks & nature': 'Yala’s wildlife safaris and tea country', Cultural: 'the ancient cities of Kandy and Sigiriya' },
    activities: ['Sightseeing', 'Food', 'Road trips', 'Water sports', 'Wellness'],
    budgetMin: 40000, budgetMax: 75000,
    travelModes: ['Flight'], travelTimeHours: 3, domestic: false,
    recommendedDuration: { min: 5, max: 8 }, typicalPace: 'slow',
    suitableStayTypes: ['hotel', 'rental'],
  },
  {
    name: 'Manali',
    profile: { Beach: 0.05, Mountains: 0.9, City: 0.2, 'Parks & nature': 0.8, Cultural: 0.2, Adventure: 0.85, Nightlife: 0.2, Romantic: 0.5 },
    highlights: { Mountains: 'the Solang and Rohtang valley views', 'Parks & nature': 'the pine forests around Old Manali', Adventure: 'paragliding, river rafting and trekking routes' },
    activities: ['Trekking', 'Adventure', 'Sightseeing', 'Cafés', 'Road trips'],
    budgetMin: 12000, budgetMax: 25000,
    travelModes: ['Road', 'Flight'], travelTimeHours: 12, domestic: true,
    recommendedDuration: { min: 4, max: 6 }, typicalPace: 'either',
    suitableStayTypes: ['hotel', 'rental'],
  },
  {
    name: 'Shimla',
    profile: { Beach: 0.05, Mountains: 0.85, City: 0.3, 'Parks & nature': 0.75, Cultural: 0.2, Adventure: 0.3, Nightlife: 0.15, Romantic: 0.6 },
    highlights: { Mountains: 'the Ridge and Jakhu hill views', 'Parks & nature': 'pine-forest walks around the Mall Road', Romantic: 'colonial-era cafés and toy-train rides' },
    activities: ['Sightseeing', 'Cafés', 'Road trips', 'Relaxing'],
    budgetMin: 10000, budgetMax: 20000,
    travelModes: ['Road', 'Train'], travelTimeHours: 8, domestic: true,
    recommendedDuration: { min: 3, max: 5 }, typicalPace: 'slow',
    suitableStayTypes: ['hotel'],
  },
  {
    name: 'Rishikesh',
    profile: { Beach: 0.05, Mountains: 0.7, City: 0.15, 'Parks & nature': 0.75, Cultural: 0.35, Adventure: 0.8, Nightlife: 0.1, Romantic: 0.25 },
    highlights: { Mountains: 'the Himalayan foothills along the Ganges', Adventure: 'white-water rafting and bungee jumping', 'Parks & nature': 'riverside forest trails' },
    activities: ['Adventure', 'Wellness', 'Trekking', 'Water sports'],
    budgetMin: 8000, budgetMax: 18000,
    travelModes: ['Road', 'Train'], travelTimeHours: 7, domestic: true,
    recommendedDuration: { min: 3, max: 5 }, typicalPace: 'either',
    suitableStayTypes: ['hotel', 'rental'],
  },
  {
    name: 'Coorg',
    profile: { Beach: 0.05, Mountains: 0.7, City: 0.15, 'Parks & nature': 0.85, Cultural: 0.2, Adventure: 0.35, Nightlife: 0.1, Romantic: 0.75 },
    highlights: { 'Parks & nature': 'coffee plantations and the Western Ghats forests', Mountains: 'Abbey Falls and Raja’s Seat viewpoints', Romantic: 'plantation-stay resorts' },
    activities: ['Sightseeing', 'Trekking', 'Cafés', 'Relaxing'],
    budgetMin: 10000, budgetMax: 22000,
    travelModes: ['Road'], travelTimeHours: 6, domestic: true,
    recommendedDuration: { min: 3, max: 5 }, typicalPace: 'slow',
    suitableStayTypes: ['hotel', 'rental'],
  },
  {
    name: 'Munnar & Kerala backwaters',
    profile: { Beach: 0.3, Mountains: 0.6, City: 0.2, 'Parks & nature': 0.9, Cultural: 0.4, Adventure: 0.3, Nightlife: 0.1, Romantic: 0.85 },
    highlights: { 'Parks & nature': 'Munnar’s tea gardens and Eravikulam valley trails', Mountains: 'the Western Ghats hill views around Munnar', Romantic: 'Alleppey houseboat stays on the backwaters' },
    activities: ['Sightseeing', 'Relaxing', 'Wellness', 'Food'],
    budgetMin: 15000, budgetMax: 32000,
    travelModes: ['Flight', 'Road'], travelTimeHours: 6, domestic: true,
    recommendedDuration: { min: 4, max: 7 }, typicalPace: 'slow',
    suitableStayTypes: ['hotel', 'rental'],
  },
  {
    name: 'Andaman Islands',
    profile: { Beach: 0.9, Mountains: 0.05, City: 0.2, 'Parks & nature': 0.6, Cultural: 0.15, Adventure: 0.6, Nightlife: 0.2, Romantic: 0.8 },
    highlights: { Beach: 'Radhanagar and Elephant beach', Adventure: 'scuba diving and snorkelling at Havelock', Romantic: 'secluded island resorts' },
    activities: ['Water sports', 'Sightseeing', 'Relaxing', 'Adventure'],
    budgetMin: 30000, budgetMax: 55000,
    travelModes: ['Flight'], travelTimeHours: 4, domestic: true,
    recommendedDuration: { min: 5, max: 7 }, typicalPace: 'slow',
    suitableStayTypes: ['hotel', 'rental'],
  },
  {
    name: 'Udaipur',
    profile: { Beach: 0.05, Mountains: 0.2, City: 0.75, 'Parks & nature': 0.2, Cultural: 0.85, Adventure: 0.15, Nightlife: 0.25, Romantic: 0.9 },
    highlights: { Cultural: 'the City Palace and Jagdish Temple', Romantic: 'Lake Pichola sunset boat rides', City: 'the old-city bazaars around the lake' },
    activities: ['Sightseeing', 'Culture', 'Food', 'Shopping', 'Cafés'],
    budgetMin: 15000, budgetMax: 35000,
    travelModes: ['Flight', 'Train', 'Road'], travelTimeHours: 4, domestic: true,
    recommendedDuration: { min: 3, max: 5 }, typicalPace: 'slow',
    suitableStayTypes: ['hotel'],
  },
  {
    name: 'Jaipur',
    profile: { Beach: 0.05, Mountains: 0.1, City: 0.8, 'Parks & nature': 0.15, Cultural: 0.9, Adventure: 0.2, Nightlife: 0.3, Romantic: 0.35 },
    highlights: { Cultural: 'Amer Fort and the City Palace', City: 'the pink-city bazaars and Hawa Mahal' },
    activities: ['Sightseeing', 'Culture', 'Shopping', 'Food'],
    budgetMin: 10000, budgetMax: 22000,
    travelModes: ['Flight', 'Train', 'Road'], travelTimeHours: 5, domestic: true,
    recommendedDuration: { min: 3, max: 4 }, typicalPace: 'packed',
    suitableStayTypes: ['hotel'],
  },
  {
    name: 'Meghalaya (Northeast India)',
    profile: { Beach: 0.05, Mountains: 0.75, City: 0.15, 'Parks & nature': 0.9, Cultural: 0.3, Adventure: 0.7, Nightlife: 0.1, Romantic: 0.4 },
    highlights: { 'Parks & nature': 'the living root bridges and Cherrapunji waterfalls', Mountains: 'the Khasi hills viewpoints', Adventure: 'caving and canyoning in Shillong' },
    activities: ['Trekking', 'Sightseeing', 'Adventure', 'Road trips'],
    budgetMin: 18000, budgetMax: 35000,
    travelModes: ['Flight', 'Road'], travelTimeHours: 8, domestic: true,
    recommendedDuration: { min: 5, max: 7 }, typicalPace: 'either',
    suitableStayTypes: ['hotel', 'rental'],
  },
  {
    name: 'Dubai, UAE',
    profile: { Beach: 0.5, Mountains: 0.1, City: 0.9, 'Parks & nature': 0.15, Cultural: 0.3, Adventure: 0.6, Nightlife: 0.85, Romantic: 0.5 },
    highlights: { City: 'the Downtown skyline and Dubai Mall', Nightlife: 'the Marina and beach-club scene', Adventure: 'desert safaris and skydiving' },
    activities: ['Shopping', 'Nightlife', 'Sightseeing', 'Adventure', 'Food'],
    budgetMin: 55000, budgetMax: 110000,
    travelModes: ['Flight'], travelTimeHours: 4, domestic: false,
    recommendedDuration: { min: 4, max: 6 }, typicalPace: 'packed',
    suitableStayTypes: ['hotel'],
  },
  {
    name: 'Singapore',
    profile: { Beach: 0.2, Mountains: 0.05, City: 0.9, 'Parks & nature': 0.3, Cultural: 0.6, Adventure: 0.3, Nightlife: 0.5, Romantic: 0.4 },
    highlights: { City: 'Marina Bay and Orchard Road', Cultural: 'Chinatown, Little India and the Peranakan heritage trail' },
    activities: ['Sightseeing', 'Food', 'Shopping', 'Culture'],
    budgetMin: 60000, budgetMax: 120000,
    travelModes: ['Flight'], travelTimeHours: 6, domestic: false,
    recommendedDuration: { min: 4, max: 6 }, typicalPace: 'packed',
    suitableStayTypes: ['hotel'],
  },
  {
    name: 'Ladakh',
    profile: { Beach: 0.05, Mountains: 0.95, City: 0.1, 'Parks & nature': 0.7, Cultural: 0.3, Adventure: 0.85, Nightlife: 0.05, Romantic: 0.4 },
    highlights: { Mountains: 'Pangong Tso and the high-altitude passes', Adventure: 'biking Khardung La and high-altitude trekking' },
    activities: ['Road trips', 'Trekking', 'Adventure', 'Sightseeing'],
    budgetMin: 25000, budgetMax: 45000,
    travelModes: ['Flight', 'Road'], travelTimeHours: 10, domestic: true,
    recommendedDuration: { min: 6, max: 9 }, typicalPace: 'packed',
    suitableStayTypes: ['hotel', 'rental'],
  },
  {
    name: 'Pondicherry',
    profile: { Beach: 0.6, Mountains: 0.05, City: 0.4, 'Parks & nature': 0.3, Cultural: 0.55, Adventure: 0.2, Nightlife: 0.25, Romantic: 0.8 },
    highlights: { Beach: 'the Promenade and Paradise beach', Romantic: 'the French Quarter’s boutique cafés', Cultural: 'Auroville and the colonial old town' },
    activities: ['Cafés', 'Sightseeing', 'Relaxing', 'Culture'],
    budgetMin: 10000, budgetMax: 20000,
    travelModes: ['Road', 'Train'], travelTimeHours: 3, domestic: true,
    recommendedDuration: { min: 2, max: 4 }, typicalPace: 'slow',
    suitableStayTypes: ['hotel', 'rental'],
  },
  {
    name: 'Hampi',
    profile: { Beach: 0.05, Mountains: 0.2, City: 0.15, 'Parks & nature': 0.5, Cultural: 0.85, Adventure: 0.55, Nightlife: 0.1, Romantic: 0.3 },
    highlights: { Cultural: 'the Vijayanagara temple ruins', Adventure: 'boulder-hopping and coracle rides on the Tungabhadra' },
    activities: ['Sightseeing', 'Culture', 'Adventure', 'Trekking'],
    budgetMin: 8000, budgetMax: 16000,
    travelModes: ['Train', 'Road'], travelTimeHours: 8, domestic: true,
    recommendedDuration: { min: 2, max: 3 }, typicalPace: 'slow',
    suitableStayTypes: ['hotel'],
  },
  {
    name: 'Kasol & Parvati Valley',
    profile: { Beach: 0.05, Mountains: 0.8, City: 0.1, 'Parks & nature': 0.75, Cultural: 0.2, Adventure: 0.7, Nightlife: 0.2, Romantic: 0.45 },
    highlights: { Mountains: 'the Parvati valley trails', 'Parks & nature': 'the pine forests around Kasol and Tosh', Adventure: 'trekking to Kheerganga' },
    activities: ['Trekking', 'Cafés', 'Adventure', 'Relaxing'],
    budgetMin: 9000, budgetMax: 18000,
    travelModes: ['Road'], travelTimeHours: 12, domestic: true,
    recommendedDuration: { min: 4, max: 6 }, typicalPace: 'slow',
    suitableStayTypes: ['rental'],
  },
]

// Broader "experience" clusters each selectable axis feeds into. Used to
// find meaningful overlap between travellers who picked different axes —
// e.g. Mountains and Parks & nature both feed "Nature/Scenic", so a
// traveller who picked one and a traveller who picked the other can still
// share a destination that's strong on either.
export const EXPERIENCE_CLUSTERS = {
  Beach: ['Leisure', 'Scenic', 'Coastal'],
  Mountains: ['Nature', 'Scenic'],
  City: ['Culture', 'Urban'],
  'Parks & nature': ['Nature', 'Outdoors'],
  Cultural: ['Culture', 'Heritage'],
  Adventure: ['Adventure', 'Outdoors'],
  Nightlife: ['Party', 'Urban'],
  Romantic: ['Leisure', 'Scenic'],
}
